### ISSUE TITLE
To add filter by length fields Latitude and Longitude

### ISSUE THREAD

**Issue by ABiatov** [olehprylutskyi/GBIF_occurence_download#1]
В дампі даних фільтрується декілька тисяч записів з дуже грубою точністю координат.

Дивись скріншот

![image](https://github.com/ABiatov/gbif_shiny_onlineviewer/assets/13443276/d0f8770b-b9af-410e-8c9a-c005097e4a12)

**Comment by olehprylutskyi** [comment]
Можливо, це те що вказали автори даних. Можна посилання на приклади таких записів?

**Comment by olehprylutskyi** [comment]
Перевірив вибірково з-поміж знахідок з Latitude==50. Всі - коректне геопозиціонування, причин відфільтровувати такі записи немає.
https://www.gbif.org/occurrence/1274854419
https://www.gbif.org/occurrence/1274854559
https://www.gbif.org/occurrence/3017901925
Серед вибраних є записи з грубим позиціонуванням (напр. https://www.gbif.org/occurrence/3986586880), але без відомостей про його похибку. На жаль, просто викинувши їх, ми однаково не відділимо правильні від неправильних. Тому пропоную лишити все як є.
